ALTER TABLE public."DashboardDataset" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."EnergyUsagePoint" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."DeviceConsumption" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."RecentActivity" ENABLE ROW LEVEL SECURITY;
